---

- name: start consul
  become: yes
  service:
    name: consul
    state: started

- name: stop consul
  become: yes
  service:
    name: consul
    state: stopped

- name: reload consul
  become: yes
  service:
    name: consul
    state: reloaded

- name: restart consul
  become: yes
  service:
    name: consul
    state: restarted

- name: start dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: started

- name: stop dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: stopped

- name: reload dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: reloaded

- name: restart dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: restarted
